=head1 NAME

callnotes.pl - quickly create and open a notes file, for use with Alfred or other tools

=head1 SYNOPSIS

    # callnotes.pl --notes_dir /my/notes/dir --desc "String describing call subject"

=head1 DESCRIPTION

This simple script quickly creates and opens for editing a text file, named based on the current date and a descriptive string passed via the command line.

It was created to be a part of an L<Alfred|http://www.alfredapp.com/> workflow for easy triggering via a keyword.

For example, typing "cn New Client" in the Alfred hotkey input field would open the file 20141011-new-client.txt for editing.

=head1 REQUIREMENTS

Perl

L<Unicode::Normalize>

Alfred (optional)

=head1 LICENSE

This program is free software; anyone can use, redistribute, and/or
modify it under the terms of the GNU General Public License as
published by the Free Software Foundation (either version 2 of the
License, or at your option, any later version) so long as this notice
and the copyright information above remain intact and unchanged.
Selling this code in any form for any reason is expressly forbidden.

This program is distributed in the hope that it will be useful, but
WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
General Public License for more details.

You should have received a copy of the GNU General Public License
along with this software; if not, write to
        Free Software Foundation, Inc., 59 Temple Place, Suite 330,
        Boston, MA  02111-1307 USA
You may also find the license at:
        http://www.gnu.org/copyleft/gpl.html

=head1 AUTHOR

Chris Hardie <chris@chrishardie.com>

http://www.chrishardie.com/

=cut
